pub mod analyzer;
pub mod dashboard;
pub mod journal;
pub mod scanner;
pub mod settings;
pub mod strategy;
pub mod trade_terminal;

// Shared widgets
pub mod chart;
pub mod command_palette;
pub mod context_menu;
pub mod modal;
pub mod progress_bar;
pub mod search_bar;
pub mod sparkline;
pub mod table;
pub mod tag;
pub mod toast;

pub use chart::Chart;
pub use context_menu::ContextMenu;
pub use modal::Modal;
pub use progress_bar::ProgressBar;
pub use search_bar::SearchBar;
pub use sparkline::SparklineWidget;
pub use table::Table;
pub use tag::Tag;
pub use toast::Toast;
pub use toast::ToastStyle;
